[package]
name = "testing"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
premortem = { path = "../.." }
serde = { version = "1.0", features = ["derive"] }
stillwater = { path = "/Users/glen/memento-mori/stillwater" }
